### ISSUE TITLE
bazel build -c opt lyra/cli_example:encoder_main error on 20.04-Ubuntu

### ISSUE THREAD

**Issue by ngubaly** [google/lyra#116]
I got an error while building command with path: lyra-1.3.2/lyra, below is what is displayed on the terminal window:
```
ba@inspirion3580:~/Downloads/lyra-1.3.2/lyra$ bazel build -c opt lyra/cli_example:encoder_main
Starting local Bazel server and connecting to it...
INFO: Repository com_google_protobuf instantiated at:
  /home/ba/Downloads/lyra-1.3.2/WORKSPACE:26:15: in <toplevel>
Repository rule git_repository defined at:
  /home/ba/.cache/bazel/_bazel_ba/f781bedf1de12532e62c8da8cc24cae3/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
	File "/home/ba/.cache/bazel/_bazel_ba/f781bedf1de12532e62c8da8cc24cae3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
		update = _clone_or_update(ctx)
	File "/home/ba/.cache/bazel/_bazel_ba/f781bedf1de12532e62c8da8cc24cae3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
		git_ = git_repo(ctx, directory)
	File "/home/ba/.cache/bazel/_bazel_ba/f781bedf1de12532e62c8da8cc24cae3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
		_update(ctx, git_repo)
	File "/home/ba/.cache/bazel/_bazel_ba/f781bedf1de12532e62c8da8cc24cae3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
		init(ctx, git_repo)
	File "/home/ba/.cache/bazel/_bazel_ba/f781bedf1de12532e62c8da8cc24cae3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
		_error(ctx.name, cl, st.stderr)
	File "/home/ba/.cache/bazel/_bazel_ba/f781bedf1de12532e62c8da8cc24cae3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
		fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init /home/ba/.cache/bazel/_bazel_ba/f781bedf1de12532e62c8da8cc24cae3/external/com_google_protobuf' while working with @com_google_protobuf:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(git, ...)": No such file or directory
ERROR: /home/ba/Downloads/lyra-1.3.2/WORKSPACE:26:15: fetching git_repository rule //external:com_google_protobuf: Traceback (most recent call last):
	File "/home/ba/.cache/bazel/_bazel_ba/f781bedf1de12532e62c8da8cc24cae3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
		update = _clone_or_update(ctx)
	File "/home/ba/.cache/bazel/_bazel_ba/f781bedf1de12532e62c8da8cc24cae3/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
		git_ = git_repo(ctx, directory)
	File "/home/ba/.cache/bazel/_bazel_ba/f781bedf1de12532e62c8da8cc24cae3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
		_update(ctx, git_repo)
	File "/home/ba/.cache/bazel/_bazel_ba/f781bedf1de12532e62c8da8cc24cae3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
		init(ctx, git_repo)
	File "/home/ba/.cache/bazel/_bazel_ba/f781bedf1de12532e62c8da8cc24cae3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
		_error(ctx.name, cl, st.stderr)
	File "/home/ba/.cache/bazel/_bazel_ba/f781bedf1de12532e62c8da8cc24cae3/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
		fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init /home/ba/.cache/bazel/_bazel_ba/f781bedf1de12532e62c8da8cc24cae3/external/com_google_protobuf' while working with @com_google_protobuf:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(git, ...)": No such file or directory
ERROR: no such package '@com_google_protobuf//': error running 'git init /home/ba/.cache/bazel/_bazel_ba/f781bedf1de12532e62c8da8cc24cae3/external/com_google_protobuf' while working with @com_google_protobuf:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(git, ...)": No such file or directory
INFO: Elapsed time: 5.382s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ba@inspirion3580:~/Downloads/lyra-1.3.2/lyra$ 

```

**Comment by wangsamllwhite** [comment]
这个问题解决了么
